services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-init:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./dbt_retail_pipeline:/opt/airflow/dbt_retail_pipeline
      - ./logs:/opt/airflow/logs
      - C:\Users\win\.dbt:/opt/airflow/.dbt
    command: >
      bash -c "airflow db migrate &&
      airflow users create
      --username airflow
      --password airflow
      --firstname Yizuo
      --lastname Deng
      --role Admin
      --email zoe998998@gmail.com || true"

  airflow-webserver:
    build: .
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./dbt_retail_pipeline:/opt/airflow/dbt_retail_pipeline
      - ./logs:/opt/airflow/logs
      - C:\Users\win\.dbt:/opt/airflow/.dbt
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./dbt_retail_pipeline:/opt/airflow/dbt_retail_pipeline
      - ./logs:/opt/airflow/logs
      - C:\Users\win\.dbt:/opt/airflow/.dbt
    command: scheduler