SHOW VIEWS IN SCHEMA RETAIL_ANALYTICS.RAW;
SHOW TABLES IN SCHEMA RETAIL_ANALYTICS.RAW;

SELECT * FROM RETAIL_ANALYTICS.RAW.MART_REGION_PERFORMANCE;
SELECT * FROM RETAIL_ANALYTICS.RAW.MART_WEEKLY_SUMMARY LIMIT 10;
SELECT * FROM RETAIL_ANALYTICS.RAW.MART_DAILY_TREND LIMIT 10;