CREATE ROLE IF NOT EXISTS DATA_ENGINEER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER;

GRANT USAGE ON DATABASE RETAIL_ANALYTICS TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA RETAIL_ANALYTICS.RAW TO ROLE DATA_ENGINEER;

GRANT CREATE TABLE ON SCHEMA RETAIL_ANALYTICS.RAW TO ROLE DATA_ENGINEER;
GRANT CREATE VIEW ON SCHEMA RETAIL_ANALYTICS.RAW TO ROLE DATA_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA RETAIL_ANALYTICS.RAW
TO ROLE DATA_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA RETAIL_ANALYTICS.RAW
TO ROLE DATA_ENGINEER;

GRANT ROLE DATA_ENGINEER TO USER ZOE998998;