name: airflow DAG check

on:
  push:
    branches: [ main ]

jobs:
  validate-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Airflow
        run: pip install apache-airflow

      - name: Check Python syntax
        run: python -m py_compile dags/retail_analytics_pipeline_dag.py

      - name: Validate DAG import with DagBag
        run: |
          python -c "from airflow.models import DagBag; dagbag = DagBag(dag_folder='dags', include_examples=False); assert len(dagbag.import_errors) == 0, dagbag.import_errors"