name: dbt CI

on:
  push:
    branches: [ main ]

jobs:
  dbt-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: dbt parse
        run: |
          cd dbt_retail_pipeline
          dbt parse