name: dbt CI

on:
  push:
    branches: [ main ]

jobs:
  dbt-check:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Create dbt profiles
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          dbt_retail_pipeline:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: "$SNOWFLAKE_ACCOUNT"
                user: "$SNOWFLAKE_USER"
                password: "$SNOWFLAKE_PASSWORD"
                role: "$SNOWFLAKE_ROLE"
                database: "$SNOWFLAKE_DATABASE"
                warehouse: "$SNOWFLAKE_WAREHOUSE"
                schema: "$SNOWFLAKE_SCHEMA"
                threads: 4
          EOF

      - name: dbt debug
        run: |
          cd dbt_retail_pipeline
          dbt debug

      - name: dbt deps
        run: |
          cd dbt_retail_pipeline
          dbt deps

      - name: dbt parse
        run: |
          cd dbt_retail_pipeline
          dbt parse

      - name: dbt compile
        run: |
          cd dbt_retail_pipeline
          dbt compile